version: '3'
#TODO: usar .env file

services:

  editor:
    build: .
    env_file:
      - .env
    command: python app.py
    ports:
      - 5002:5002
    volumes:
      - .:/code

networks:
  default:
    external:
      name: pratoaberto