version: '3'
#TODO: usar .env file

services:

  editor:
    build: .
    env_file:
      - .env
    command: gunicorn app:app --timeout 120 --log-level DEBUG -w 1 -b 0.0.0.0:8001
    volumes:
      - .:/code

networks:
  default:
    external:
      name: pratoaberto